### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Rollbacke** [AtsumeruDev/Atsumeru#6]
Hi,

I discovered Atsumeru yesterday. What a great idea !

However, I'm not able to use it, I've an error 500.

I don't quite understand the reason.
From what I see, the process is well started:

```
root@0c04eb3f198e:/app# ps auxf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         176  3.0  0.0   7632  4104 pts/0    Ss   11:39   0:00 bash
root         184  0.0  0.0  10040  1536 pts/0    R+   11:40   0:00  \_ ps auxf
root           1  4.8  2.7 10021592 441804 ?     Ssl  11:32   0:23 java -Dserver.port=31337 -jar Atsumeru.jar
```

Here are the logs.
_There is an error, but I don't know if it's due to that._

```
# docker logs scans

     _   _
    / \ | |_ ___ _   _ _ __ ___   ___ _ __ _   _
   / _ \| __/ __| | | | '_ ` _ \ / _ \ '__| | | |
  / ___ \ |_\__ \ |_| | | | | | |  __/ |  | |_| |
 /_/   \_\__|___/\__,_|_| |_| |_|\___|_|   \__,_|

Version:  (v1.0.2)

2023-08-29 11:32:07.374  INFO 1 --- [           main] com.atsumeru.web.AtsumeruApplication     : Starting AtsumeruApplication v1.0.2 using Java 11.0.20 on 0c04eb3f198e with PID 1 (/app/Atsumeru.jar started by root in /app)
2023-08-29 11:32:07.380  INFO 1 --- [           main] com.atsumeru.web.AtsumeruApplication     : The following 1 profile is active: "production"
2023-08-29 11:32:09.171  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 31337 (http)
2023-08-29 11:32:09.182  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-08-29 11:32:09.183  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.60]
2023-08-29 11:32:09.626  INFO 1 --- [           main] org.apache.jasper.servlet.TldScanner     : At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2023-08-29 11:32:09.862  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-08-29 11:32:09.863  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2402 ms
2023-08-29 11:32:10.382  INFO 1 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure any request
2023-08-29 11:32:10.896  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 31337 (http) with context path ''
2023-08-29 11:32:10.911  INFO 1 --- [           main] com.atsumeru.web.AtsumeruApplication     : Started AtsumeruApplication in 4.196 seconds (JVM running for 4.935)
2023-08-29 11:32:10.913  INFO 1 --- [           main] AtsumeruApplication                      : Application started with command-line arguments: []
2023-08-29 11:32:10.916 ERROR 1 --- [           main] Settings                                 : Unable to load atsumeru.properties
2023-08-29 11:32:10.916  INFO 1 --- [           main] MetadataUpdateService                    : Metadata service started
2023-08-29 11:32:10.918  INFO 1 --- [           main] FoldersProperties                        : Loading folder properties file...
2023-08-29 11:32:10.919  WARN 1 --- [           main] FoldersProperties                        : Unable to load folder properties...
2023-08-29 11:32:10.920  INFO 1 --- [           main] FileWatcherConfig                        : Starting Import Filesystem Watcher...
2023-08-29 11:32:10.922  INFO 1 --- [           main] CoversSaverService                       : Covers saver service started
2023-08-29 11:32:10.923  INFO 1 --- [           main] BonjourService                           : Starting Bonjour service with name Atsumeru (v1.0.2)...
2023-08-29 11:32:10.923  INFO 1 --- [       Thread-1] FileWatcherConfig                        : Import Filesystem Watcher started!
2023-08-29 11:32:10.931  INFO 1 --- [           main] BonjourService                           : Bonjour variables: {port=31337, remote.host_name=localhost, remote.address=127.0.0.1, version=1.0.2, local.address=10.0.1.26, local.host_name=0c04eb3f198e}
2023-08-29 11:32:10.972  INFO 1 --- [           main] BonjourService                           : Bonjour service started
2023-08-29 11:32:10.978  INFO 1 --- [           main] CategoryRepository                       : Categories loaded. Took 6ms
2023-08-29 11:32:10.981  INFO 1 --- [           main] MetacategoryRepository                   : Metacategories indexed. Took 3ms
2023-08-29 11:32:17.888  INFO 1 --- [io-31337-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030x8bGC0x980x84N0x040x160x020xf90xea0x899Y0xd90xd7:0xd80xc10xfe0x7f0x040xbfm0xe10x1e*0xf90xf00x1f0x0c0xc8 ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2023-08-29 11:32:41.046  INFO 1 --- [io-31337-exec-5] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-08-29 11:32:41.046  INFO 1 --- [io-31337-exec-5] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-08-29 11:32:41.047  INFO 1 --- [io-31337-exec-5] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2023-08-29 11:32:41.079  INFO 1 --- [io-31337-exec-5] RequestLogInterceptor                    : [Private@Unknown] Requested /
```

The atsumeru part of my `docker-compose.yml` (I've added the 31337 port to bypass my reverse-proxy (traefik)) :

```
scans:
    image: atsumerudev/atsumeru:latest
    container_name: scans
    ports:
      - 31337:31337
    volumes:
      - ./scans/data/library/:/library/:rw
      - ./scans/data/config/:/app/config/:rw
      - ./scans/data/db/:/app/database/:rw
      - ./scans/data/cache/:/app/cache/:rw
      - ./scans/data/logs/:/app/logs/:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.scans-http31337.loadbalancer.server.port=31337"
      - "traefik.http.middlewares.scans-redirect-https.redirectscheme.scheme=https"
      - "traefik.http.routers.scans-http.rule=Host(`scans.myfqdn.fr`)"
      - "traefik.http.routers.scans-http.entrypoints=http"
      - "traefik.http.routers.scans-http.middlewares=scans-redirect-https"
      - "traefik.http.routers.scans-https.rule=Host(`scans.myfqdn.fr`)"
      - "traefik.http.routers.scans-https.tls.certresolver=myresolver"
      - "traefik.http.routers.scans-https.entrypoints=https"
      - "traefik.http.routers.scans-https.service=scans-http31337"
      - "traefik.http.routers.scans-https.middlewares=secHeaders@file" # hsts and co
    networks:
      net_my-network:
    restart: unless-stopped
```

My folders architecture:

```
# tree -ugp ./scans
[drwxr-xr-x root     root    ]  .
└── [drwxr-xr-x root     root    ]  data
    ├── [drwxr-xr-x root     root    ]  cache
    ├── [drwxr-xr-x root     root    ]  config
    ├── [drwxr-xr-x root     root    ]  db
    │   ├── [-rw-r--r-- root     root    ]  library.db
    │   ├── [-rw-r--r-- root     root    ]  library.db-shm
    │   ├── [-rw-r--r-- root     root    ]  library.db-wal
    │   └── [-rw-r--r-- root     root    ]  users.db
    ├── [drwxr-xr-x root     root    ]  library
    └── [drwxr-xr-x root     root    ]  logs
        ├── [-rw-r--r-- root     root    ]  requests.log
        └── [-rw-r--r-- root     root    ]  requests.log.lck

7 directories, 6 files
```

If you have any idea...

**Comment by AtsumeruDev** [comment]
@Rollbacke please, check this API url `<host:port>/api/v1/books`

It may be a little bit consfusing but (i hope, for now) there is no any of "web interface" for `Atsumeru`  

Despite that you need to use [AtsumeruManager](https://github.com/AtsumeruDev/AtsumeruManager) for server managing (and reading) and/or [AtsumeruAndroid](https://github.com/AtsumeruDev/AtsumeruAndroid) if you want to read your books on `Android`

Also, you can build and use `AtsumeruManager` as [WebApp](https://github.com/AtsumeruDev/AtsumeruManager#webapp)

**Comment by Rollbacke** [comment]
Oh damn. I didn't understand anything.
Indeed, everything works.
I was wondering why there were two github repositories for the same app, now I get it.
Sorry...

**Comment by Rollbacke** [comment]
So I'll end on that, it would be cool to have a Docker image for AtsumeruManager :D
I will try to make a Dockerfile based on Atsumeru's, I could suggest it to you.

**Comment by AtsumeruDev** [comment]
@Rollbacke preparing some new update for manager and will try to wrap WebApp version into Docker image. If you have any other questions about Atsumeru, fell free to ask them on https://t.me/atsumeru_talk
